<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Task;
use Carbon\Carbon;

class TaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tasks = [
            [
                'task_name' => 'Design User Registration UI',
                'task_desc' => 'Create wireframes and design mockups for user registration page with form validation.',
                'task_deadline' => Carbon::now()->addDays(7),
                'task_modulo' => 1,
                'task_assignedto' => 3,
                'task_priority' => 2,
                'task_accessmod' => 0,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Integrate Stripe API',
                'task_desc' => 'Implement Stripe payment gateway integration with test transactions.',
                'task_deadline' => Carbon::now()->addDays(14),
                'task_modulo' => 2,
                'task_assignedto' => 8,
                'task_priority' => 3,
                'task_accessmod' => 1,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Develop Product Search',
                'task_desc' => 'Create search functionality with filters by category, price range, and ratings.',
                'task_deadline' => Carbon::now()->addDays(10),
                'task_modulo' => 3,
                'task_assignedto' => 7,
                'task_priority' => 2,
                'task_accessmod' => 0,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Implement Transfer Validation',
                'task_desc' => 'Create validation rules for fund transfers including daily limits and balance checks.',
                'task_deadline' => Carbon::now()->addDays(21),
                'task_modulo' => 4,
                'task_assignedto' => 5,
                'task_priority' => 3,
                'task_accessmod' => 1,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Add Utility Bill Providers',
                'task_desc' => 'Integrate with major utility providers for electricity, water, and gas bill payments.',
                'task_deadline' => Carbon::now()->addDays(28),
                'task_modulo' => 5,
                'task_assignedto' => 14,
                'task_priority' => 2,
                'task_accessmod' => 1,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Implement Biometric Auth',
                'task_desc' => 'Add fingerprint and facial recognition authentication for mobile app.',
                'task_deadline' => Carbon::now()->addDays(35),
                'task_modulo' => 6,
                'task_assignedto' => 5,
                'task_priority' => 3,
                'task_accessmod' => 1,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Design EHR Database Schema',
                'task_desc' => 'Create database structure for electronic health records with proper relationships.',
                'task_deadline' => Carbon::now()->addDays(25),
                'task_modulo' => 7,
                'task_assignedto' => 17,
                'task_priority' => 2,
                'task_accessmod' => 1,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Develop Calendar Interface',
                'task_desc' => 'Create interactive calendar for appointment booking with time slot management.',
                'task_deadline' => Carbon::now()->addDays(18),
                'task_modulo' => 8,
                'task_assignedto' => 9,
                'task_priority' => 2,
                'task_accessmod' => 0,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Create Insurance Claim Form',
                'task_desc' => 'Design and develop digital insurance claim submission form with document upload.',
                'task_deadline' => Carbon::now()->addDays(30),
                'task_modulo' => 9,
                'task_assignedto' => 20,
                'task_priority' => 2,
                'task_accessmod' => 1,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Build Enrollment Dashboard',
                'task_desc' => 'Create admin dashboard for managing student enrollments and applications.',
                'task_deadline' => Carbon::now()->addDays(12),
                'task_modulo' => 10,
                'task_assignedto' => 10,
                'task_priority' => 2,
                'task_accessmod' => 0,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Develop Grade Calculator',
                'task_desc' => 'Create automated grade calculation system with weighting and curve options.',
                'task_deadline' => Carbon::now()->addDays(15),
                'task_modulo' => 11,
                'task_assignedto' => 11,
                'task_priority' => 2,
                'task_accessmod' => 1,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Implement QR Code Attendance',
                'task_desc' => 'Develop QR code generation and scanning system for class attendance.',
                'task_deadline' => Carbon::now()->addDays(20),
                'task_modulo' => 12,
                'task_assignedto' => 13,
                'task_priority' => 1,
                'task_accessmod' => 0,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Create Barcode Generator',
                'task_desc' => 'Develop system to generate unique barcodes for inventory items.',
                'task_deadline' => Carbon::now()->addDays(8),
                'task_modulo' => 13,
                'task_assignedto' => 15,
                'task_priority' => 2,
                'task_accessmod' => 0,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Set Up Low Stock Notifications',
                'task_desc' => 'Configure automatic email and SMS alerts for low inventory levels.',
                'task_deadline' => Carbon::now()->addDays(22),
                'task_modulo' => 14,
                'task_assignedto' => 17,
                'task_priority' => 3,
                'task_accessmod' => 0,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'task_name' => 'Build Inventory Analytics',
                'task_desc' => 'Create dashboard with charts and graphs for inventory turnover and performance.',
                'task_deadline' => Carbon::now()->addDays(25),
                'task_modulo' => 15,
                'task_assignedto' => 18,
                'task_priority' => 1,
                'task_accessmod' => 1,
                'delete_status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($tasks as $task) {
            Task::create($task);
        }
    }
}
